### ISSUE TITLE
`/eth/v1/beacon/states/{state_id}/committees/{epoch}` unclear

### ISSUE THREAD

**Issue by mcdee** [ethereum/eth2.0-APIs#108]
The comment for `epoch` on this endpoint states: "Epoch for which to calculate committees. Defaults to beacon state epoch."  This doesn't fit with our existing usage of endpoints, where none of the other path values are optional.

I can think of a couple of solutions.  We could make two endpoints:

- `/eth/v1/beacon/states/{state_id}/committees` which returns the committees for the current epoch as per the `state_id`
- `/eth/v1/beacon/states/{state_id}/committees/{epoch}` which returns the committees for the specified `epoch` and `state_id`

If it is felt that this stretches the sub-resource definition past breaking point then as an alternative we could go with just the first endpoint and change `epoch` to an optional query parameter.

**Comment by mpetrunic** [comment]
> If it is felt that this stretches the sub-resource definition past breaking point then as an alternative we could go with just the first endpoint and change epoch to an optional query parameter.

I'm in favour of this

**Comment by rolfyone** [comment]
I think that the epoch being an optional query parameter is a good idea, it fits better with the usage

**Comment by mpetrunic** [comment]
@mcdee is this resolved? Can we close?

**Comment by mcdee** [comment]
Yep.
