### ISSUE TITLE
Few schemas definitions have custom format with current OpenAPI specification

### ISSUE THREAD

**Issue by Magicking** [ethereum/eth2.0-APIs#49]
Types are described as here https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#data-types

Some schemas such as Root / Hex / Signatures have an invalid format such as `hex` (non-existent) or `bytes` (I guess a typo and should be `byte`), see https://github.com/ethereum/eth2.0-APIs/blob/master/types/primitive.yaml#L33

Other malformed schemas may exist in the repository.

**Comment by mpetrunic** [comment]
According to spec, that's allowed:
> However, to support documentation needs, the format property is an open string-valued property, and can have any value.

**Comment by Magicking** [comment]
Indeed, mea-culpa for that wrong information :) the problem it raises is that code generators using this specification don't know how to handle that and don't validate the specification nor knows how to handle theses custom format (tried with github/getkin/kin-openapi).

And there is a bunch of them https://github.com/OAI/OpenAPI-Specification/blob/master/IMPLEMENTATIONS.md

**Comment by mpetrunic** [comment]
Might be worth raising issue on github/getkin/kin-openapi to ignore unknown formats on those (should fallback to type whose are all per spec).

We are actually using spectral to lint open api files and swagger-cli to bundle. I think, we would merge it if you open PR to remove formats all together (since we are using hex encoding, putting byte format could assume base64 encoding).

**Comment by Magicking** [comment]
After looking more carefully at kin-openapi, there is an option to disable the custom format validation, I may have overlooked that in the documentation or the other tool I'm using it with [oapi-codegen](https://github.com/deepmap/oapi-codegen).

Regarding the PR, indeed the format seems redundant with the pattern already specifying a hex-encoded value with the 0x prefix already.
