### ISSUE TITLE
Committess at slot: subscriptions and duties

### ISSUE THREAD

**Issue by paulhauner** [ethereum/eth2.0-APIs#52]
We've recently found that in order to avoid a `BeaconState` read we need to thread the `get_committee_count_at_slot` through the validator duties and up into the subnet subscription.

The reason is that the allocation of an attestation to a subnet is *fork-dependant*. I.e., two attestations with the same `index` and `slot`, but different `beacon_block_root` can be required to be published in two different subnets (only in rare circumstances). There's a more in-depth explanation here: https://github.com/sigp/lighthouse/pull/1257#issuecomment-645085765.

I'd be interested in hearing peoples thoughts on including this `get_committee_count_at_slot` value in:

- `/validator/duties/{epoch}/attester`
- `/validator/beacon_committee_subscriptions`

The reasoning being is that it prevents the BN from needing to know the active validator count for `attestation.data.beacon_block_root` when processing a `/validator/beacon_committee_subscriptions` request.

On our end, we've called the field `committee_count_at_slot` but we're open to change :)

**Comment by mcdee** [comment]
In the API revamp we have a call `/v1/validator/duties/attester/{epoch}` which returns:

```
data [
  {
    public_key: byte[]
    committee_index: uint64
    committee_length: uint64
    validator_committee_index: uint64
    slot: uint64
  }
]
```

Is `committee_count_at_slot` the same as `committee_length` _i.e._ the number of validators in the committee, or is it something else?

(And in case you're wondering, `validator_committee_index` is the index of the validator inside the committee; it's a horrible name but we couldn't come up with anything else that sounded better, so suggestions appreciated.)

**Comment by paulhauner** [comment]
> Is committee_count_at_slot the same as committee_length?

Unfortunately not. `committee_count_at_slot` represents the *count of committees* at a slot, whilst `committee_length` represents the *size of a committee* at a slot.

For example, if you wanted rougly the number of validators that will attest in a slot you would do: `committee_count_at_slot * committee_length`. 

> we couldn't come up with anything else that sounded better

Nor can I :(

I don't like `committee_count_at_slot` either, but also can't think of anything better.

**Comment by mcdee** [comment]
Gotcha.  So i can think of three ways of doing this.  My preferred way would be to add this as top-level data, _i.e._:

```
data {
  **committee_count: uint64**
  attesters: {
    public_key: byte[]
    committee_index: uint64
    committee_length: uint64
    validator_committee_index: uint64
    slot: uint64
  }
}
```

Alternatively we could put the committee count in each attester object (keeps the returned info as a simple array, but repeats ourself) or just put it in another endpoint (but that then requires the user to make multiple calls and most use cases for the endpoint will require this information so we're forcing the user to do more work than necessary.  @mpetrunic are you happy with the above solution?

Also, from the info in the comment you linked it sounds like this value won't change within a single epoch as its based on active validator count, but if that may not be the case let me know and we'll make it a per-slot array or similar.

**Comment by paulhauner** [comment]
I'm perfectly fine with top level data or including it in the `attesters` object.

I'd prefer not to have a separate endpoint since it's something we need for each attestation produced. It's nice to keep all the data required to produce an attestation in the same call to avoid race-conditions if the shuffling updates during a fork.

> it sounds like this value won't change within a single epoch as its based on active validator count

Correct; on any given chain the value is consistent across all slots in an epoch. No need for a per-slot array :)

**Comment by mpetrunic** [comment]
It seems like we are trying to make VC to be BN cache. Any reason why BN can't have simple cache with (epoch + fork) => committee_count_at_slot mapping and fallback in case of missing cache would be "expensive" state read?

If we do wanna go this route, I would put it inside every duty as it doesn't involve changing response type dramatically (endpoint is expected to return array)

**Comment by rolfyone** [comment]
> I would put it inside every duty as endpoint is expected to return array and it would be nice to keep some conventions

the beauty of the data wrapper is we can put this outside that as 'metadata' kind of concept, and it won't break the return... This is why things got wrapped, for messages and other metadata, so i think it'd be a great use-case...

**Comment by paulhauner** [comment]
> When you are processing /validator/beacon_committee_subscriptions request, you don't have info on
attestation.data.beacon_block_root.

It's debatable as whether or not you should have access to `attestation.data.beacon_block_root`. You shouldn't *re*-propagate an attestation unless `beacon_block_root` is known, but the spec does not define restrictions as to what should be initially broadcast AFAIK. The most obvious choice to me would be "don't publish anything you wouldn't have re-propagated", which means you *would* have access to `beacon_block_root`.

That being said, what I propose allows for always publishing the attestation on the correct subnet *without* needing to know `beacon_block_root`.

> you can only rely on BNs head chain

Relying on the BNs head chain is what creates the risk of publishing on the wrong subnet.

> In case of bug reorg that would change subnet, VC would have to get new attester duties and send another /validator/beacon_committee_subscriptions request.

The goal is to ensure that the subnet that is chosen is consistent with the attestation.

Just because a validator has published an attestation to a BN on a different fork doesn't necessarily mean that the attestation should be disregarded by that BN.

**Comment by paulhauner** [comment]
I had a chat with @mpetrunic out-of-band and he convinced me that I might be wrong here. I need to do some more digging on our end, I'll re-open if/when I figure out what we need.

Apologies if this turns out to be a waste of time!

**Comment by paulhauner** [comment]
I am following this up at #81
