### ISSUE TITLE
Api docs deployment

### ISSUE THREAD

**Issue by mpetrunic** [ethereum/eth2.0-APIs#54]
Current status:
- github pages hosted on master branch
- every file is downloaded on it's own
- slow initialization speed
- once we release we would have to use develop branch and we won't be able to see progress

Ideas:
- add to ci task to bundle all files into single blob (this would be useful for converting other formats as well)
- publish current development render from gh-pages branch and using bundle instead of separate files (faster loading speed)
- have some hosting service/server where we would host released api docs (are we gonna have some stable releases?)
- publish every PR somewhere and use some github bot to comment url of build

**Comment by mpetrunic** [comment]
@djrtwo does EF already has some services to host static files? 

I can create PR for CI to bundle and publish master on gh-pages (to render current development) but we would still require some server to host site with some stable version of api.

**Comment by djrtwo** [comment]
cc: @Souptacular

**Comment by skmgoldin** [comment]
If you care to do versioned releases of the API spec here on Github, you could host the bundle file with the release. You could do it all from CI, too. Not sure if that suits your requirements.

https://help.github.com/en/github/administering-a-repository/about-releases

**Comment by mpetrunic** [comment]
> If you care to do versioned releases of the API spec here on Github, you could host the bundle file with the release. You could do it all from CI, too. Not sure if that suits your requirements.
> 
> https://help.github.com/en/github/administering-a-repository/about-releases

Thats an option too, in that case we would deploy swagger-ui on gh-pages and use top bar dropdown to choose bundle dev/v1/v2 🤔

**Comment by skmgoldin** [comment]
Having versioned releases would be quite nice for my use-case (API conformance testing tool). Not necessary, but nice.
