### ISSUE TITLE
Response object types in generated code are not named

### ISSUE THREAD

**Issue by skmgoldin** [ethereum/eth2.0-APIs#65]
Using the `openapi-generator` go module with this spec produces [numbered (not named!) response object types](https://github.com/INFURA/eth2-comply/blob/main/pkg/eth2spec/model_inline_response_200_11_data.go). This leads to two difficulties for me:

1. My code is harder to read.
2. Every time I update my generated code with the latest updates from the spec hosted here, I have to manually ensure none of the numbered response types have shifted to have new meanings.

It would be nicer if, for example, the `GetBlockAttestations` operation had a response type like `GetBlockAttestationsResponse` instead of `InlineResponse20011`. I know it is possible to generate named response types; the OpenAPI spec that Teku generates from its own codebase produces named responses, for instance.

By the way, slight shill: [eth2-comply](https://github.com/INFURA/eth2-comply) is now ready to use. 🙂

**Comment by mpetrunic** [comment]
i did that because of data wrappers but yeah it probably makes sense to create named response with data wrapper so generated code looks nicer. Might be some other prop to indicate response name

**Comment by mpetrunic** [comment]
I've expected it would infer name from operation name and request/response suffix
