### ISSUE TITLE
validator duties on separate endpoints...

### ISSUE THREAD

**Issue by rolfyone** [ethereum/eth2.0-APIs#69]
When splitting out the validator client from teku, there's been questions raised about why the API would split out validator duties retrieval for attestations and proposals, because from the code perspective they're both needed to be called to figure out what the validator needs to do.

Would there be value in combining `/eth/v1/validator/duties/proposer/{epoch}` and `/eth/v1/validator/duties/attester/{epoch}` into something like `/eth/v1/validator/duties/{epoch}`?

**Comment by mcdee** [comment]
At the beginning of an epoch a validator needs to obtain proposer duties for the current epoch and attester duties for the next epoch, hence the split.

There is also the secondary difference that attester duties are requested for a subset of validators, and proposer duties are provided for all validators (as it is bounded to 32 responses any request from a validator client with a larger number of validators would be extraneous work).

**Comment by ajsutton** [comment]
A validator should be requesting both attester and proposer duties one epoch ahead.  There's no reason to delay requesting proposer duties until the current epoch.

Given that you're sending the validator public keys to request attester duties, it seems awkward to then have to separately request all proposer duties for the epoch and manually filter and adds the overhead of an additional request.

**Comment by mpetrunic** [comment]
> A validator should be requesting both attester and proposer duties one epoch ahead. There's no reason to delay requesting proposer duties until the current epoch.

According to spec, proposer duties aren't safe to fetch one epoch ahead:

> The beacon chain shufflings are designed to provide a minimum of 1 epoch lookahead on the validator's upcoming committee assignments for attesting dictated by the shuffling and slot. Note that this lookahead does not apply to proposing, which must be checked during the epoch in question.

**Comment by ajsutton** [comment]
hmm, I thought that change had been undone again but it appears not.  That does make more sense to have the two APIs separate then.

**Comment by rolfyone** [comment]
i think we all agree that these need to be separate, so closing.
