### ISSUE TITLE
Using status code 403 for business logic related responses can be confusing

### ISSUE THREAD

**Issue by lucassaldanha** [ethereum/eth2.0-APIs#71]
Looking at the `getAggregatedAttestation` [definition](https://ethereum.github.io/eth2.0-APIs/#/Validator/getAggregatedAttestation), the HTTP status code 403 (Forbidden) is being used to represent an application-specific state (Beacon node was not assigned to aggregate on that subnet).

For any deployment scenario in which APIs being protected by an authorization system, it will be hard to differentiate when the 403 is due to unauthorized access or because the beacon node isn't subscribed to a subnet.

I suggest that we use a less common status code to represent application-state based responses. Or maybe add some extra info on the response so clients can differentiate them.

**Comment by rolfyone** [comment]
not sure how adventurous we want to get with codes, but it sounds like a 421...

https://httpstatuses.com/421

**Comment by mpetrunic** [comment]
My next goal is to specify error responses. Maybe we can use 400 and specify error in response?

**Comment by rolfyone** [comment]
that would be ok too, just probably 403 has a specific meaning which we're kind of not in line with...
