### ISSUE TITLE
Represent uint64 as string

### ISSUE THREAD

**Issue by mpetrunic** [ethereum/eth2.0-APIs#9]
Even though json definition doesn't have limit in int size, it will cause troubles in tools like Postman and Swagger where values greater than int53 will be rounded down. If we define it as string, json parser might not assume native types in different languages

**Comment by paulhauner** [comment]
This seems reasonable to me. Eth1 has set the precedence of using `0x..` ascii-hex for uint256, perhaps it could be the same for uint64?

**Comment by djrtwo** [comment]
hmm, 0x sucks for readability though :/

String is my relatively naive vote

**Comment by mpetrunic** [comment]
We are representing as string everywhere and prysmatic is doing the same
