### ISSUE TITLE
validator/beacon_commitee_subscriptions does not support persistent subscriptions

### ISSUE THREAD

**Issue by ajsutton** [ethereum/eth2.0-APIs#98]
Validators may ask the beacon node to subscribe to an attestation subnet for three reasons:

 1. The validator is producing an attestation at some future slot and needs to ensure peers are available to publish to
 2. The validator is the aggregator for a committee at some future slot and needs to subscribe to the subnet gossip topic
 3. The validator selects a random subnet (not committee) to create a persistent subscription to. see https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/validator.md#phase-0-attestation-subnet-stability In this case the beacon node must subscribe to the gossip topic AND publish the subnet ID in its MetaData and ENR.

Currently the `/eth/v1/validator/beacon_committee_subscriptions` API can handle the first two, but there doesn't appear to be any way to signal that a subscription is persistent at should be reported via MetaData and ENR. It's also awkward to have to try and reverse engineer a committee ID out of the subnet ID the validator randomly selects (and may not be possible given committee ID to subnet ID mapping requires the number of active validators).

My suggestion would be that the request body is changed to something like:

```
[
  {
    "subnet_index": uin64,
    "committee_index": uint64,
    "slot": uint64,
    "subscription_type": ("attestation" | "aggregate" | "persistent")
  }
]
```

One of `subnet_index` or `committee_index` would be required.  In all cases, the node should ensure peers are available on the subnet.  When `subscription_type` is `aggregate ` or `persistent` the node must subscribe to the gossip topic for the subnet.  When `subscription_type` is `persistent` the node should advertise the subnet subscription in it's `MetaData` and `ENR`.

Most likely validator clients would always provide a `subnet_index` for `persistent` subscriptions and `commitee_index` for `attestation` and `aggregate` subscriptions but I don't see any reason not to allow either if the Validator Client is somehow able to determine it.

The `committees_at_slot` value is dropped as it doesn't appear to be needed for anything and calculating it requires the number of active validators.

**Comment by paulhauner** [comment]
We use the following info for the `validator/beacon_commitee_subscriptions` endpoint and compute the persistent committees in the BN using the `validator_index`:

```rust
struct BeaconCommitteeSubscription {
    pub validator_index: u64,
    pub committee_index: u64,
    pub committees_at_slot: u64,
    pub slot: Slot,
    pub is_aggregator: bool,
}
```

I didn't realize we deviated from the spec without creating an issue here, apologies for that.

**Comment by mcdee** [comment]
Although https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/validator.md#phase-0-attestation-subnet-stability is in the validator guide, it feels to me that the third item is more of a beacon node requirement than that of a validator.  This is enforced by the fact that the section talks about the node's ENRs, which is part of the beacon node not the validator client.

Given that the validator's state is not an input to the selection function, it seems to make sense for the beacon node to handle the long-term subnet subscriptions and it not to be part of validator client's work, let alone part of the API.  Or am I missing something?

**Comment by mpetrunic** [comment]
Any reason to include persistent subscription to that endpoint?
Seems like that would just complicate endpoint implementation unnecessary, since BN can track active validators in epoch trough `/eth/v1/validator/beacon_committee_subscriptions` and maintain random subscriptions accordingly.

Few questions for example:
- does VC on restart subscribes to another persistent subscription or should it also keep track of current active ones in db?
- should VC also keep a list of upcoming hard forks or query beacon node for it so that it can create another persistent subscription?

**Comment by ajsutton** [comment]
The beacon node needs to pick one random subnet per validator.  Implying the number of validators it should do that for from other calls to `beacon_commitee_subscriptions` should work and that does make it easier to deal with upcoming hard forks. I'll give that a go and see if it works.  Previously we'd been pretty careful to ensure the beacon node doesn't know anything about how many validators it runs.

We don't store persistent subscriptions in the db, but our validator is in the same process as the beacon node so if it exits the subscriptions were torn down anyway.  We're currently working on supporting running it as an external process so that is a more interesting issue to deal with now.

I still don't understand how the Validator Client calculates `committees_at_slot`. I'd have expected that to be the output of https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/beacon-chain.md#get_committee_count_per_slot which requires the number of active validators as input.  Is it meaning some other value?  I'm also unclear what the beacon node is using it for.

**Comment by mpetrunic** [comment]
> I still don't understand how the Validator Client calculates `committees_at_slot`. I'd have expected that to be the output of https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/beacon-chain.md#get_committee_count_per_slot which requires the number of active validators as input. Is it meaning some other value? I'm also unclear what the beacon node is using it for.

You get that from attester duty response^^ :slightly_smiling_face:

**Comment by ajsutton** [comment]
And more importantly, if the beacon node is giving it to us, why do we have to give it back to the beacon node? Shouldn't it already know?

**Comment by mpetrunic** [comment]
> Oh that's new - we don't have that. Why do we need it?
> And more importantly, if the beacon node is giving it to us, why do we have to give it back to the beacon node? Shouldn't it already know?

https://github.com/ethereum/eth2.0-APIs/pull/81 explains it pretty well

**Comment by ajsutton** [comment]
Ah thanks. That makes sense.

**Comment by AgeManning** [comment]
@ajsutton - How did you go with this? 

As @paulhauner mentioned, our API includes a validator index. So for each subscription we know which validator is making the request. Because we know which validator is making a request we can determine the unique validators connected to the beacon node.

It seems to me like a poor design to make the beacon node have to infer (with possible error) which validators and how many are connected via the rate of calls. 

Adding a validator index seems to be a more general case. Clients wishing to infer from number of calls can still do so, and we can continue with our current API and have the BN know which validators are connecting. The overhead of a single uint seems very minimal here.

**Comment by ajsutton** [comment]
@AgeManning We followed your lead and include the validator ID in the subscription request and it all works out.  


Also just implemented a `--p2p-subscribe-all-subnets-enabled` so that providers like Infura can just have a pool of nodes that subscribe to all attestations and handle aggregate requests and not direct any subscription requests to other nodes to reduce their bandwidth requirements.

**Comment by AgeManning** [comment]
Oh yeah nice. That's a good idea! 

Seeing as there are two of us that use this API. I'll make a PR to update the API spec.
